# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    # Real life sizes 
    # {id: 0, size: 0.0667, name: tag_0},
    # {id: 1, size: 0.1333, name: tag_1},
    # {id: 2, size: 0.1333, name: tag_2},
    # {id: 3, size: 0.1333, name: tag_3},
    # {id: 4, size: 0.1333, name: tag_4},
    # {id: 5, size: 0.2666, name: tag_5},
    # {id: 6, size: 0.2666, name: tag_6},
    # {id: 7, size: 0.2666, name: tag_7},
    # {id: 8, size: 0.2666, name: tag_8}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: "target_bundle",
      layout:
      [
        {id: 0, size: 0.0667, x: 0, y: 0, z: 0, qw: 0, qx: 0, qy: 0, qz: 1},
        {id: 1, size: 0.1333, x: 0, y: 0.15, z: 0, qw: 0, qx: 0, qy: 0, qz: 1},
        {id: 2, size: 0.1333, x: 0.15, y: 0, z: 0, qw: 0, qx: 0, qy: 0, qz: 1},
        {id: 3, size: 0.1333, x: 0, y: -0.15, z: 0, qw: 0, qx: 0, qy: 0, qz: 1},
        {id: 4, size: 0.1333, x: -0.15, y: 0, z: 0, qw: 0, qx: 0, qy: 0, qz: 1},
        {id: 5, size: 0.2666, x: 0.23375, y: 0.23375, z: 0, qw: 0, qx: 0, qy: 0, qz: 1},
        {id: 6, size: 0.2666, x: 0.23375, y: -0.23375, z: 0, qw: 0, qx: 0, qy: 0, qz: 1},
        {id: 7, size: 0.2666, x: -0.23375, y: -0.23375, z: 0, qw: 0, qx: 0, qy: 0, qz: 1},
        {id: 8, size: 0.2666, x: -0.23375, y: 0.23375, z: 0, qw: 0, qx: 0, qy: 0, qz: 1}
      ]
    }
  ]
